### ISSUE TITLE
I want to make it so that by clicking on my pet with the compass, which is the server menu from the ItemJoin plugin, I can sit on my pet. 

### ISSUE THREAD

**Issue by Pikachu2p** [MyPetORG/MyPet#1503]
Hi! Help please. I want to make it so that by clicking on my pet with the compass, which is the server menu from the ItemJoin plugin, I can sit on my pet. My riding skill is turned on and I checked it with a regular compass, everything works, but when I click the compass from the itemjoin plugin, then this player does not sit on the pet and cannot ride. I tried to write the name of the menu compass itself, but it didn't work, in Itemjoin I tried to create a regular compass without signatures and it still doesn't work, I wrote to the itemjoin developer, but there is no answer yet. I hope you can help me

**Comment by Jakllp** [comment]
The way this probably works is that the compass used for the itemjoin-menu checks for an interact event (aka a click)
It then checks if it is the itemjoin-compass and not just a regular compass

After that it will cancel the click event (so that no other plugin will use it) and do the itemjoin-compass-action

There is no real way for MyPet to fix this (and the same probably holds true for itemjoin as well as this is not "the only way to do it" but the most common one and basically the expected one)

MyPet-Example: If you left-click (hit) a pet with a lead it will show you the info and not damage the pet. It could theoretically damage the pet but it would be counter intuitive to damage your pet in order to see its info.


I hope this explanation helped to clear things up

**Comment by Pikachu2p** [comment]
I think I understand you. Thanks for the answer :)

**Comment by Pikachu2p** [comment]
Is it possible to use the pcm mouse buttons instead of any object and sit on a pet? That is, enter the right click instead of the compass.

**Comment by Jakllp** [comment]
This is actually a feature that will be coming with the next build (trying to finalize that today - no promises tho)

**Comment by Pikachu2p** [comment]
Good
