### ISSUE TITLE
Disable pet attack behavior, disable skill trees.

### ISSUE THREAD

**Issue by austinmpask** [MyPetORG/MyPet#1643]
# Feature request

What part of MyPet needs this?
- [ X] the plugin itself
- [ X] the Skilltree Creator
- [ ] the website

## Is your feature request related to a problem? Please describe

This plugin is clunky for integrations of cosmetic only pets. In my instance I do not care about a skill tree, and want pets to exist purely cosmetically.

## Describe the solution you'd like

Config options to disable skill tree entirely, and disable attacking behavior

## Describe alternatives you've considered

_A clear and concise description of any alternative solutions or features you've considered._

## Additional context

_Add any other context or screenshots about the feature request here._

**Bukkit/Spigot/Bungee Build/Version:**

**MyPet Build/Version:**

**Comment by Jakllp** [comment]
## Attack
In order for a pet to even be able to attack it needs a skilltree that contains a combat skill of any kind (damage/ranged).  
## Skilltrees in general
There are two workarounds but no direct way to just disable them:
### Workaround 1 (no skills whatsoever)
- Delete all skilltrees out of the skilltrees folder
- To then get rid of the "choose a skilltree" message, go into config.yml and set `Skilltree.AutomaticAssignment` and `Skilltree.ChooseOnce` to true. You can also set `Skilltree.RandomAssignment` to true but it shouldn't really effect it (on my test server it was already true which is why I mention it)
### Workaround 2 (maybe some skills)
- Follow Workaround 1
- Create a new skilltree via the [Skilltree-Creator](https://wiki.mypet-plugin.de/systems/skilltrees/skilltreecreator) and add the skills you need/want to it (obviously harmless ones like Backpack or PickUp and not Combat/Ranged as you don't want them to attack)


I hope this helped

**Comment by austinmpask** [comment]
Thank you. I had worked around by automatically choosing the skilltree and disabling the message but will follow your steps to disable attacks.
