### ISSUE TITLE
[Skill] Protection >> fire / fall damage / suffocation

### ISSUE THREAD

**Issue by Phreag** [MyPetORG/MyPet#555]
Is it possible to make originally fireresistant pets like blazes, pigzombies etc fireproof?
They would be a big benefit when you are mining with your pet and it always dies in lava...

**Comment by zerafox** [comment]
I think this might be better as either a Configuration Option or a 'skill' that can be added into a Skill-Tree.
Perhaps this could be used as some sort of "Epic Pet Status" within a tree when reaching a certain level, or the option for different servers to have different pets, if any pets, fireproof.

If pets were into the swimming thing, (I know their Wolf AI has them float) I would suggest a 'water breath' equivalent option due to Squid and Guardians.

**Comment by xXKeyleXx** [comment]
The skill will provide protection against fire / fall damage / suffocation.

**Comment by zerafox** [comment]
I had a further thought on this and perhaps this would be easier as a Skill built into a Skill Tree.
"Resistance"
With options for the available reasons to negate/avoid damage from certain sources: Fall, Fire, Lava, Suffocation?, etc;

I felt that our Rabbit pets needed some sort of Fall Resistance when I heard a player make comment about his Rabbit always falling off cliffs. It would make sense to be able to grant this same resistance to Parrots.
While Fire Damage resistance to Blazes, etc;

Doing something in this manner, on a Skill rather than a configuration may be an easier and more flexible approach.

**Comment by zerafox** [comment]
#1237 New ticket opened by Dev, closing this ticket due to duplicate/similiar idea for sake of order and cleanliness.

**Comment by Felina-Lain** [comment]
Hello, sorry to re-open this, but I see it marked as completed but could not find references of a Protection or Resistance skill in the wiki, to add to my skill trees, so I thought to ask here how to make this work?

**Comment by Jakllp** [comment]
It wasn't closed because it's done but because someone else mentioned it here:
https://github.com/MyPetORG/MyPet/issues/1237
